name: proyectofinalbdtools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - ipykernel
  - geopandas
  - shapely
  - pyarrow
  - sqlalchemy
  - psycopg2
  - pymongo
  - python-dotenv
  - pip
  - pip:
      - prefect
