docker psname: proyectofinalbdtools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - polars
  - pyarrow
  - duckdb
  - scipy
  - scikit-learn
  - imbalanced-learn
  - matplotlib
  - seaborn
  - plotly
  - geopandas
  - shapely
  - folium
  - contextily
  - sqlalchemy
  - psycopg2-binary
  - geoalchemy2
  - pymongo
  - python-dotenv
  - pydantic
  - joblib
  - pip:
      - prefect>=2.20
      - ydata-profiling
